Fix folly/gen/test/ParallelBenchmark.cpp under gcc8 with -Wshadow
Summary:
[Folly] Fix `folly/gen/test/ParallelBenchmark.cpp` under gcc8 with `-Wshadow`.

```
In file included from folly/gen/test/Bench.h:19,
                 from folly/gen/test/ParallelBenchmark.cpp:26:
folly/Benchmark.h: In instantiation of 'typename std::enable_if<std::is_invocable<Lambda, unsigned int>::value>::type folly::addBenchmark(const char*, const char*, Lambda&&) [with Lambda = <lambda(unsigned int)>; typename std::enable_if<std::is_invocable<Lambda, unsigned int>::value>::type = void]':
folly/gen/test/ParallelBenchmark.cpp:96:279:   required from here
folly/Benchmark.h:185:10: error: declaration of 'start' shadows a global declaration [-Werror=shadow]
folly/gen/test/ParallelBenchmark.cpp:83:6: note: shadowed declaration is here
```

Reviewed By: Orvid

Differential Revision: D13605092

fbshipit-source-id: ac791942edbfeda70809d4ab80d21bb3ff7dd8de